# 运行在 Velocity 上时的配置

# 不要更改本设置，否则会造成配置重置，后果自负。
# 更新新的插件版本也会导致配置重置。请务必提前备份配置文件
version = "@VERSION@"

# 插件提示前缀（可以使用 & 符号）
plugin-prefix = "VelocityTitle"

# 是否开启 Debug 模式
debug-mode = true

# 数据库设置
[database]
mode = "Embedded" # 数据库工作方式
driver = "org.h2.Driver" # 数据库驱动地址
url = "jdbc:h2:file:./data/velocitytitle;DB_CLOSE_DELAY=-1;MODE=MYSQL;" # 数据库 URL 地址
username = "root" # 用户名
password = "password" # 密码
