modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/maple/FlashyTitles/issues"

[[mods]]
modId="flashy-titles"
version="${version}"
displayName="FlashyTitles"
description='''
FlashyTitles NeoForge 端 - 群组服务器称号同步系统
支持动态称号效果和跨服同步
'''
authors="maple"
displayURL="https://github.com/maple/FlashyTitles"

[[dependencies.flashy-titles]]
modId="neoforge"
mandatory=true
versionRange="[21.1.0,)"
ordering="NONE"
side="SERVER"

[[dependencies.flashy-titles]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="SERVER"
